apiVersion: apps/v1
kind: Deployment
metadata:
  name: biashara-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: biashara
  template:
    metadata:
      labels:
        app: biashara
    spec:
      containers:
        - name: biashara
          image: wyclif1043/biashara:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
